# --- ЭТАП 1: Сборка ---
FROM node:20-alpine as build-stage

WORKDIR /app

COPY src/package*.json ./
RUN npm install

COPY src/ .
# Создает папку /app/dist с готовыми файлами
RUN npm run build

# --- ЭТАП 2: Раздача статики ---
FROM nginx:alpine

# Копируем собранный фронтенд из первого этапа в папку Nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Копируем кастомный конфиг Nginx (важно для SPA)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]